server:
  port: 1208
  servlet:
    context-path: /music

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/music_app?createDatabaseIfNotExist=true&useSSL=true"
    username: root
    password: root
    driverClassName: "com.mysql.cj.jdbc.Driver"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "bs16wH/6EZddgDhSHr/9T90Zhdk12i5ZgJI5EU63Jb3yaiySUmzgQIkHk0itJDk7/n"
  valid-duration: 1800
  refreshable-duration: 7200