server:
  port: 1208
  servlet:
    context-path: /music




spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/music-app?createDatabaseIfNotExist=true&useSSL=true"
    username: root
    password: root
    driverClassName: "com.mysql.cj.jdbc.Driver"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true